export default {
    CONTAINER_TYPES: {
        QUEUE: 'queue',
        CONTINUE_WATCHING: 'continue_watching',
        FEATURED: 'featured',
        REGULAR: 'regular',
        SHORT_FORM: 'short_form',
        PLAYLIST: 'playlist',
        CHANNEL: 'channel',
        LINEAR: 'linear',
    },
    REGULAR_CONTAINER_TYPES: [
        'regular',
        'queue',
        'continue_watching',
        'channel',
    ],
    QUEUE_CONTAINER_ID: 'queue',
    HISTORY_CONTAINER_ID: 'continue_watching',
    RECOMMENDED_CONTAINER_ID: 'recommended_for_you',
    RECENTLY_ADDED_CONTAINER_ID: 'recently_added',
    LIVE_NEWS_CONTAINER_ID: 'live_news',
    COMING_SOON_CONTAINER_ID: 'coming_soon',
    PERSONAL_CONTAINER_IDS: [
        'recommended_for_you',
        'continue_watching',
        'queue',
    ],
    CLIP_CONTENT_TYPE: 'c',
    SERIES_CONTENT_TYPE: 's',
    VIDEO_CONTENT_TYPE: 'v',
    LIVE_CONTENT_TYPE: 'l',
    SEARCH_CAST: 'search',
    FEATURED_CONTAINER_ID: 'featured',
    SCREENSAVER_CONTAINER_ID: 'featured',
    MOST_POPULAR_TV_SHOWS: 'most_popular_tv_shows',
    PARENTAL_SEARCH_TRIGGERS: [
        'sex',
        'xxx',
        'adult',
        'after hours',
        'porn',
        'sexy',
        'adult',
        'sexy',
        'lesbian',
        'erotic',
        'nude',
        'naked',
        'fuck',
        'tit',
        'dirty',
        'anal',
        'playboy',
        'pussy',
        '18+',
    ],
    RELATED_CONTENTS_LIMIT: 10,
    OTT_CONTAINER_DISPLAY_COUNT: 5,
    OTT_TILE_DISPLAY_COUNT: 9,
    OTT_TILE_DISPLAY_COUNT_LOW_END_DEVICES: 7,
    OTT_INITIAL_TILE_LOAD_COUNT: 9,
    HOMEPAGE_INIT_CONTAINER_COUNT: 6,
    LIVE_NEWS_CONTAINER_INIT_LOAD_COUNT: 40,
    FIRST_TIME_LOAD_ROW_NUM: 7,
    NAV_LIST_SECTION: 'nav_list',
    GRID_SECTION: 'grid',
    NOTIFICATION_DISMISS_TIMEOUT: 5000,
    VIDEO_BUFFERING_THRESHOLD: 50,
    PLAYER_STALL_TIMEOUT: 60000,
    SHOW_SCREENSAVER_THRESHOLD: 5,
    SHOW_STILL_WATCHING_THRESHOLD: 300,
    STORE_USER_FIELDS: [
        'email',
        'fbId',
        'hasPassword',
        'name',
        'token',
        'userId',
        'authType',
        'status',
        'fbUserToken',
    ],
    BACK_EVENT: 'BACK_EVENT',
    OTT_SEEK_SPEEDS_INTERVALS: [8, 64, 512],
    OTT_PLAYER_STATES: {
        init: 'player_init',
        playing: 'player_playing',
        buffering: 'player_buffering',
        paused: 'player_paused',
        forward: 'player_seeking_forward',
        rewind: 'player_seeking_rewind',
    },
    OTT_PLAYER_CONTENT_TYPE: {
        ad: 'content_ad',
        video: 'content_video',
        trailer: 'content_trailer',
    },
    PLAYER_STATES: {
        none: 'player_none',
        inited: 'player_inited',
        playing: 'player_playing',
        paused: 'player_paused',
        seeking: 'player_seeking',
        completed: 'player_completed',
    },
    PLAYER_CURSOR_IDLE_TIMEOUT: 3000,
    PLAYER_CONTROL_FIRST_SHOW_TIMEOUT: 5000,
    IS_WEBMAF: false,
    COOKIE_OTT_RATING_PROMPT: 'o_rp',
    COOKIE_ADULT_SEARCH_NOTIFICATION: 'pc_asn',
    COOKIE_REDIRECT_URL: 'r_url',
    COOKIE_DEVICE_ID: 'deviceId',
    COOKIE_MAINTENANCE_NOTIFICATION: 'maintenance',
    COOKIE_BELOW_MIN_AGE_COPPA: 'coppa_underage',
    COOKIE_NATIVE_ANDROID_VERSION: 'o_cnav',
    COOKIE_DEVICE_DEAL: 'o_dd',
    COOKIE_ISD: 'o_isd',
    COOKIE_RSD: 'o_rsd',
    COOKIE_ZIPCODE: 'zip',
    COOKIE_CONTAINERS_CACHE_KEY: 'containersCacheKey',
    COOKIE_WEB_ROUTE: 'web_route',
    WEB_CAPTION_SETTINGS: 'web_cc',
    LD_CUSTOM_CAPTIONS_SETTINGS: 'cc_settings',
    LD_DEFAULT_CAPTIONS: 'default_cc',
    DEFAULT_CAPTION_LANGUAGE: 'English',
    USER_PREFERENCES: 'userPreferences',
    START_POS_QUERY: 'startPos',
    BREAKPOINTS: { sm: 375, md: 768, lg: 960, xl: 1170, xxl: 1440 },
    TUBI_PLAYER_EVENTS: {
        ready: 'tb_ready',
        setupError: 'tb_setupError',
        error: 'tb_error',
        seek: 'tb_seek',
        seeked: 'tb_seeked',
        play: 'tb_play',
        pause: 'tb_pause',
        complete: 'tb_complete',
        adPlay: 'tb_adPlay',
        adPause: 'tb_adPause',
        adTime: 'tb_adTime',
        adStart: 'tb_adStart',
        adComplete: 'tb_adComplete',
        adPodComplete: 'tb_adPodComplete',
        adPodEmpty: 'tb_adPodEmpty',
        adError: 'tb_adError',
        adClick: 'tb_adClick',
        fullscreen: 'tb_fullscreen',
        time: 'tb_time',
        mute: 'tb_mute',
        volume: 'tb_volume',
        captionsListChange: 'tb_captionsListChange',
        allSubtitlesAvailable: 'tb_subtitlesAvailable',
        subtitleChange: 'tb_subtitleChange',
        qualityListChange: 'tb_qualityListChange',
        qualityChange: 'tb_qualityChange',
        visualQualityChange: 'tb_visualQualityChange',
        firstFrame: 'tb_firstFrame',
        bufferStart: 'tb_bufferStart',
        bufferEnd: 'tb_bufferEnd',
        bufferChange: 'tb_bufferChange',
        warning: 'tb_warning',
        userPlay: 'tb_userPlay',
        userPause: 'tb_userPause',
        userSeek: 'tb_userSeek',
        metadata: 'tb_metadata',
        background: 'tb_background',
        foreground: 'tb_foreground',
    },
    TRAILER_AD_BREAKS: [],
    SEEK_TOLERANCE_OFFSET: 20,
    RESTART_CLOSE_OFFSET: 10,
    MAX_RESEEK_ATTEMPTS: 4,
    SEEK_TYPES: {
        arrowLeft: 'remote left arrow',
        arrowRight: 'remote right arrow',
        forward: 'forward button',
        backward: 'backward button',
        stepForward: 'step forward button',
        stepBackward: 'step backward button',
    },
    legalExpOverridePrefix: 'x-exp-',
    legalExpOverrides: [
        'x-content-likes',
        'x-enable-syscat',
        'x-featured-rotation',
        'x-exp-abtest',
    ],
    REMOTE_CONFIG_OVERRIDE_KEY: 'x-remoteconfig',
    tubiLogoURL:
        'https://cdn.adrise.tv/tubitv-assets/img/tubi_open-graph-512x512.png',
    tubiLogoSize: '512',
    INVERTED_PAGE_PATHNAMES: [
        'static',
        'account',
        'login',
        'signup',
        'activate',
        'register',
        'preference',
    ],
    IGNORE_INVERTED_PAGE_PATHNAMES: ['/static/supported-browsers'],
    DEFAULT_PROFILE_PIC_URL:
        'https://cdn.adrise.tv/tubitv-assets/img/default_profile_pic.png',
    HIDE_TOP_NAV_PATHNAMES: [
        'activate',
        'watch',
        'signup-a',
        'login',
        'signup',
    ],
    STATIC_TOP_NAV_PATHNAMES: ['account', 'static', 'preference'],
    genderOptionsMessages: {
        male: {
            defaultMessage: 'Male',
            id: 'src/common/constants/constants:male',
        },
        female: {
            defaultMessage: 'Female',
            id: 'src/common/constants/constants:female',
        },
        other: {
            defaultMessage: 'Other',
            id: 'src/common/constants/constants:other',
        },
    },
    OTT_STALE_DURATION: 10800000,
    ONE_WEEK: 604800000,
    ONE_HOUR: 3600000,
    ONE_MONTH: 2592000000,
    FULLSCREEN_CHANGE_EVENTS: [
        'fullscreenchange',
        'webkitfullscreenchange',
        'mozfullscreenchange',
        'MSFullscreenChange',
    ],
    CAST_APPLICATION_ID: 'AB2C7FED',
    ENABLE_MAINTENANCE_NOTIFICATION: false,
    BACK_FROM_PLAYBACK_TO_DETAIL: 'playbackToDetail',
    BACK_FROM_DETAIL_TO_HOME: 'detailToHome',
    BACK_FROM_LIVE_PLAYBACK_TO_HOME: 'liveToHome',
    BACK_FROM_TUBI_TO_ENTRANCE: 'tubiToEntrance',
    BACK_FROM_CONTAINER_TO_HOME: 'containerToHome',
    WEBMAF_STATUS_BACKGROUND: 'background',
    WEBMAF_STATUS_FOREGROUND: 'foreground',
    BLOCK_HOT_KEYS: true,
    FREEZED_EMPTY_ARRAY: [],
    FREEZED_EMPTY_OBJECT: {},
    COMCAST_LOGIN_ERROR: 'LOGIN_001',
    COMCAST_ROUTE_CHANGE_ERROR: 'ROUTE_CHANGE_001',
    COMCAST_DEBOUNCE_TIME: 300,
    IS_PERFORMANCE_COLLECTING_ON: true,
    OTT_SEARCH_MAX_KEYWORD_LEN: 30,
    OTT_SEARCH_RESULTS_CACHE_DURATION: 300000,
    SEARCH_RESULTS_CACHE_COUNT: 10,
    IS_MIN_HOME_DATA_EXPERIMENT_ON: false,
    PERF_METRIC_KEYS: [
        'domComplete',
        'domContentLoadedEventEnd',
        'domInteractive',
    ],
    PLAYER_PERF_METRIC_KEYS: [
        'ManifestLoaded',
        'LevelLoaded',
        'FragLoaded',
        'timeupdate',
    ],
    COMPUTED_PERF_METRICS: {
        documentDownloadTime: 'documentDownloadTime',
        ttfb: 'ttfb',
    },
    RESOURCE_TYPES: {
        js: { extensions: ['.js'] },
        css: { extensions: ['.css'] },
        image: { extensions: ['.jpg', '.png', '.svg'] },
    },
    COMCAST_EXIT_MESSAGE: 'ExitMessage.TUBI',
    HOME_DATA_SCOPE: {
        all: 'all',
        firstScreen: 'firstScreen',
        loadRest: 'loadRest',
    },
    DEFAULT_LOCATION: 'All Locations',
    IS_SENDBEACON_ON: true,
    IS_YOUBORA_ACTIVE: true,
    IS_SSR_ENABLED: true,
    SENTRY_EXCEPTION: 'exception',
    SENTRY_MESSAGE: 'message',
    ANALYTICS_COMPONENTS: {
        navigationDrawerComponent: 'navigation_drawer_component',
        containerComponent: 'category_component',
        autoplayComponent: 'auto_play_component',
        relatedComponent: 'related_component',
        episodeVideoListComponent: 'episode_video_list_component',
        searchResultComponent: 'search_result_component',
    },
    TRACK_NAVIGATE_WITHIN_PAGE_WAIT_TIME: 3000,
    FB_AUTH_COOKIE: 'auth',
    FB_SIGNIN_EXISTING_USER: 'fb-signin-eu',
    FB_SIGNUP_NEW_USER: 'fb-signup-nu',
    FB_COPPA_COOKIE: 'fb-coppa',
    FB_NEED_AGE: 'need-age',
    DEVICE_LANGUAGE: 'DEVICE_LANGUAGE',
    REGISTRATION_FORM_FIELD_NAMES: {
        FIRST_NAME: 'firstName',
        LAST_NAME: 'lastName',
        EMAIL: 'email',
        PASSWORD: 'password',
        PASSWORD2: 'password2',
        BIRTH_MONTH: 'birthMonth',
        BIRTH_DAY: 'birthDay',
        BIRTH_YEAR: 'birthYear',
        GENDER: 'gender',
        SUBMIT: 'submit',
        AGE: 'age',
    },
    SSO_CHOICES: { SSO_FACEBOOK: 'FACEBOOK', SSO_GOOGLE: 'GOOGLE' },
    NOT_SPECIFIED: 'NOT_SPECIFIED',
    FIRETV_PMR_CW_TITLE_MIN_BUILD_CODE: 629,
    HYB_APP_NATIVE_BACK_MIN_BUILD_CODE: 151,
    HYB_APP_NATIVE_NEW_ANALYTICS_MIN_BUILD_CODE: 295,
    HYB_APP_NATIVE_DRM_MIN_BUILD_CODE: 345,
    FIRETV_HDMI_CONNECT_HANDLER_BUILD_CODE: 496,
    LOGIN_WITH_AMAZON_MIN_BUILD_CODE: 623,
    TITLE_TAG_MAX_LENGTH: 75,
    CONTENT_MODES: {
        movie: 'movie',
        tv: 'tv',
        linear: 'linear',
        queue: 'queue',
        all: 'all',
        espanol: 'latino',
    },
    CONTAINER_GROUPINGS: {
        CHANNELS: 'Channels',
        COLLECTIONS: 'Collections',
        GENRES: 'Genres',
        POPULAR: 'Popular',
    },
    DEBUGGER_LAUNCHER_URL:
        'https://remote-debugger-1.staging-public.tubi.io/scripts/launcher.js',
    AUTO_START_QUERY_PARAM_FROM_LINK: 'start',
    DEEPLINK_KIDSMODE_IDENTIFIER: 'kidsmode',
    EMAIL_ADDRESS: {
        CONTENT_SUBMISSIONS: 'content-submissions@tubi.tv',
        PARTNERSHIPS: 'partnerships@tubi.tv',
    },
    IS_NAVIGATION_IMPROVEMENT_ENABLED: true,
    USE_HLS_FOR_RESUME: false,
    COUNTDOWN_SECONDS_FOR_FULLSCREEN: 10,
    KEY_REPEAT_DEBOUNCE_TIME: 200,
    MINIMUM_AGE_FOR_COPPA_COMPLIANCE: 13,
    IS_HOMEGRID_HIGH_END_DESIGN_ENABLED: false,
    IS_PLATFORM_CHECK_FOR_DRM: false,
    IS_PLATFORM_SUPPORT_WEBP: true,
    IS_RESOURCE_TIMING_SAMPLE_RATE_ENABLED: true,
    MINIMUM_APP_VERSION_FOR_DRM: { FIRETV_HYB: 345, ANDROIDTV: 483, PS4: 1 },
    SHOW_UPDATE_APP_MODAL_BELOW_VERSION: {},
    IS_TRAILER_DISABLED: false,
    IS_COPPA_ENABLED: true,
    IS_COPPA_FETCH_USER_AGE_ENABLED: true,
    OPEN_APP_STORE_AVAILABLE_PLATFORM_AND_BUILD_CODE: [
        ['ANDROIDTV', 525],
        ['FIRETV_HYB', 529],
    ],
    IS_SUPPORT_ENABLE_EXTERNAL_SDKS_BRIDGE: false,
    IS_PLATFORM_SUPPORT_SCREENSAVER: false,
    IS_TOP_NAV_ENABLED: true,
    IS_DEEPLINK_RESUME_POSITION_ENABLED: false,
    NETWORK_HEALTH: { GOOD: 'good', ERROR: 'error' },
    ACTIVE_AREA: { keyboard: 0, grid: 1 },
    ENABLE_OTT_MOUSE_EVENTS: false,
    IS_BUTTON_ANIMATION_ENABLED: false,
    VIEWPORT_TYPE: { mobile: 'mobile', tablet: 'tablet', desktop: 'desktop' },
    VIEWPORT_BREAKPOINTS: { tablet: 1170, mobile: 768 },
    IS_COMCAST_LOGIN_ENABLED: false,
};
